[package]
name = "firebase-rust"
version = "0.1.0"
authors = ["am <tsushimori@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.89"
serde_derive = "1.0.89"
serde_json = "1.0.39"
yup-oauth2 = "1.0.11"
reqwest = "0.9.10"
